// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOjLr1B5XB0x8uwIg9_p2P-8i5Jokc08',
    appId: '1:339597039541:web:b3f65eb711a158a74b6bfc',
    messagingSenderId: '339597039541',
    projectId: 'supermarketpro-e0b5e',
    authDomain: 'supermarketpro-e0b5e.firebaseapp.com',
    storageBucket: 'supermarketpro-e0b5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDEyDrBnb2Ie3wtEZl45T89-x4t_ormM',
    appId: '1:339597039541:android:11b7e741dd405d774b6bfc',
    messagingSenderId: '339597039541',
    projectId: 'supermarketpro-e0b5e',
    storageBucket: 'supermarketpro-e0b5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFOOQuORTy5eDg-YDFrCe25BouknWXVE',
    appId: '1:339597039541:ios:beddb9ebdde00a114b6bfc',
    messagingSenderId: '339597039541',
    projectId: 'supermarketpro-e0b5e',
    storageBucket: 'supermarketpro-e0b5e.firebasestorage.app',
    iosBundleId: 'com.example.alisveris',
  );
}
